
[config]
additional_profiles = [
  "multi-phase-tests",
  "ci-coverage-tasks",
  "ci-all-build-tasks",
  "publish-pre-cleanup",
]

[env]
CARGO_MAKE_DUCKSCRIPT_SKIP_UNSTABLE_TESTS = true

[tasks.clean-target]
condition = { files_exist = ["./target"] }
script = '''
#!@duckscript
rm -Rf ./target
'''

[tasks.test-multi-phases-flow]
dependencies = ["clean-target"]

[tasks.test-custom]
alias = "test-scripts"

[tasks.test-script]
cwd = ".."
install_crate = false
command = "cargo"
args = ["make", "--no-workspace", "test-script", "${@}"]

[tasks.test-scripts]
cwd = ".."
install_crate = false
command = "cargo"
args = ["make", "--no-workspace", "test-scripts"]

[tasks.pre-coverage]
alias = "clean-target"
